import type { PermissionKey, SubscriptionPlan } from "./types";

export const productPrinciples = [
  "Every person matters: people are never reduced to numbers, leads or revenue.",
  "Church autonomy: each church controls its structure, terminology, data and workflows.",
  "Denomination neutrality: KingdomFlow stores canonical keys and displays tenant labels.",
  "Spiritual boundaries: the product never replaces pastors, prayer, fellowship or spiritual leadership.",
  "Financial integrity: churches configure their own payment destinations in future billing phases.",
  "Privacy by design: pastoral, child, financial and welfare data require strict scoped access.",
  "Configuration with safeguards: audit trails, tenant isolation and sensitive protections cannot be disabled.",
];

export const permissionGroups = [
  {
    key: "church_administration",
    label: "Church administration",
    permissions: [
      "tenant.view",
      "tenant.update",
      "tenant.branding.manage",
      "tenant.terminology.manage",
      "tenant.security.manage",
      "tenant.data.manage",
      "tenant.subscription.view",
      "tenant.subscription.manage",
      "settings.view",
      "settings.manage",
    ],
  },
  {
    key: "organization",
    label: "Organizational structure",
    permissions: [
      "organization.view",
      "organization.create",
      "organization.update",
      "organization.move",
      "organization.archive",
      "organization.assign_leader",
      "organization.view_descendants",
      "organization.manage",
    ],
  },
  {
    key: "branches",
    label: "Branches",
    permissions: [
      "branch.view",
      "branch.create",
      "branch.update",
      "branch.archive",
      "branch.assign_leader",
      "branch.view_consolidated",
      "branch.manage",
    ],
  },
  {
    key: "users_access",
    label: "Users and access",
    permissions: [
      "user.view",
      "user.invite",
      "user.update",
      "user.suspend",
      "user.reactivate",
      "user.remove_from_tenant",
      "role.view",
      "role.create",
      "role.update",
      "role.archive",
      "role.assign",
      "role.remove",
      "role.manage",
      "permission.view",
      "permission.manage",
      "delegation.view",
      "delegation.create",
      "delegation.approve",
      "delegation.revoke",
    ],
  },
  {
    key: "governance",
    label: "Governance",
    permissions: [
      "governance.view",
      "governance.manage",
      "governance.appointment.create",
      "governance.appointment.approve",
      "governance.transfer.create",
      "governance.transfer.approve",
      "governance.suspension.create",
      "governance.suspension.approve",
      "governance.resolution.view",
      "governance.resolution.manage",
    ],
  },
  {
    key: "members_visitors",
    label: "Members and visitors foundations",
    permissions: [
      "people.view",
      "people.create",
      "people.update",
      "people.archive",
      "people.merge",
      "people.export_basic",
      "people.export_sensitive",
      "people.export_children",
      "people.export_all_branches",
      "household.view",
      "household.manage",
      "member.view",
      "member.create",
      "member.update",
      "member.archive",
      "member.export",
      "member.manage",
      "visitor.view",
      "visitor.create",
      "visitor.update",
      "visitor.manage",
      "new_convert.view",
      "new_convert.create",
      "new_convert.manage",
      "follow_up.view",
      "follow_up.assign",
      "follow_up.manage",
      "follow_up.view_notes",
      "consent.view",
      "consent.manage",
      "transfer.create",
      "transfer.approve",
      "child.view_basic",
      "child.view_sensitive",
      "child.manage",
      "child.export",
      "guardian.manage",
      "form.manage",
      "import.people",
      "duplicate.manage",
    ],
  },
  {
    key: "pastoral_care",
    label: "Pastoral care foundations",
    permissions: [
      "pastoral_case.create",
      "pastoral_case.view_assigned",
      "pastoral_case.view_unit",
      "pastoral_case.view_all",
      "pastoral_case.update",
      "pastoral_case.refer",
      "pastoral_case.assign",
      "pastoral_case.close",
      "pastoral_case.reopen",
      "pastoral_case.view_sensitive_notes",
      "pastoral_case.view_restricted_notes",
      "pastoral_case.view_highly_confidential",
      "pastoral_case.export_summary",
      "pastoral_case.export_detailed",
      "pastoral_case.view",
      "pastoral_case.manage",
      "prayer_request.create",
      "prayer_request.view",
      "prayer_request.assign",
      "prayer_request.manage",
      "prayer.export",
      "testimony.review",
      "testimony.publish",
      "counselling.manage",
      "pastoral_visit.manage",
      "bereavement.manage",
      "welfare_request.create",
      "welfare_request.view",
      "welfare_request.assess",
      "welfare_request.approve",
      "welfare_request.manage",
      "welfare.export",
      "professional_referral.manage",
      "safeguarding.case.create",
      "safeguarding.case.view",
      "safeguarding.case.manage",
      "safeguarding.case.refer",
      "safeguarding.case.close",
      "safeguarding.settings.manage",
      "safeguarding.audit.view",
      "safeguarding.export",
    ],
  },
  {
    key: "small_groups",
    label: "Cells and fellowships foundations",
    permissions: [
      "small_group.view",
      "small_group.view_all",
      "small_group.create",
      "small_group.update",
      "small_group.manage",
      "small_group.archive",
      "small_group.assign_leader",
      "small_group.membership.manage",
      "small_group.join_request.manage",
      "small_group.transfer.manage",
      "small_group.attendance.record",
      "small_group.attendance.view",
      "small_group.report.submit",
      "small_group.report.review",
      "small_group.report.approve",
      "small_group.report.return",
      "small_group.report.lock",
      "small_group.giving.record",
      "small_group.giving.view",
      "small_group.giving.verify",
      "small_group.multiplication.manage",
      "small_group.settings.manage",
      "small_group.public_directory.manage",
      "small_group.export",
    ],
  },
  {
    key: "programmes",
    label: "Programmes and learning foundations",
    permissions: [
      "programme.view",
      "programme.create",
      "programme.update",
      "programme.publish",
      "programme.approve",
      "programme.archive",
      "programme.cohort.manage",
      "programme.trainer.assign",
      "programme.enrolment.view",
      "programme.enrolment.manage",
      "programme.enrolment.approve",
      "programme.payment.view",
      "programme.payment.verify",
      "programme.scholarship.view",
      "programme.scholarship.manage",
      "programme.scholarship.approve",
      "programme.attendance.capture",
      "programme.attendance.view",
      "programme.material.manage",
      "programme.assignment.manage",
      "programme.assessment.manage",
      "programme.grade",
      "programme.result.release",
      "programme.result.moderate",
      "programme.certificate.issue",
      "programme.certificate.revoke",
      "programme.graduation.manage",
      "programme.report.view",
      "programme.report.export",
      "programme.settings.manage",
      "programme.manage",
    ],
  },
  {
    key: "finance",
    label: "Finance foundations",
    permissions: [
      "finance.view_summary",
      "finance.view_detailed",
      "finance.transaction.create",
      "finance.transaction.approve",
      "finance.transaction.post",
      "finance.budget.create",
      "finance.budget.approve",
      "finance.bank_details.manage",
      "finance.audit.view",
      "finance.view",
      "finance.manage",
    ],
  },
  {
    key: "departments_volunteers",
    label: "Departments and volunteers foundations",
    permissions: [
      "service.view",
      "service.create",
      "service.update",
      "service.approve",
      "service.publish",
      "service.cancel",
      "service.plan.manage",
      "service.order.manage",
      "service.sermon.view",
      "service.sermon.manage",
      "service.worship.manage",
      "service.report.create",
      "service.report.review",
      "service.report.approve",
      "service.report.export",
      "department.view",
      "department.create",
      "department.update",
      "department.archive",
      "department.assign_leader",
      "department.manage_members",
      "department.manage",
      "volunteer.view",
      "volunteer.manage",
      "volunteer.approve",
      "volunteer.availability.manage",
      "roster.view",
      "roster.create",
      "roster.publish",
      "roster.confirm",
      "roster.replace",
      "roster.manage",
      "rehearsal.manage",
      "equipment_checklist.manage",
      "media_request.manage",
      "protocol.manage",
      "service.incident.create",
      "service.incident.view",
      "service.incident.manage",
      "service.settings.manage",
    ],
  },
  {
    key: "communication",
    label: "Communication foundations",
    permissions: [
      "communication.view",
      "communication.create",
      "communication.approve",
      "communication.publish",
      "communication.send_all",
      "communication.send_scoped",
    ],
  },
  {
    key: "events_missions_children",
    label: "Events, missions and children foundations",
    permissions: [
      "event.view",
      "event.create",
      "event.update",
      "event.approve",
      "event.publish",
      "event.cancel",
      "event.registration.view",
      "event.registration.manage",
      "event.registration.approve",
      "event.payment.view",
      "event.payment.verify",
      "event.ticket.issue",
      "event.check_in",
      "event.check_out",
      "event.session.manage",
      "event.volunteer.manage",
      "event.speaker.manage",
      "event.transport.manage",
      "event.accommodation.manage",
      "event.meals.manage",
      "event.security.manage",
      "event.safeguarding.manage",
      "event.incident.create",
      "event.incident.view",
      "event.incident.manage",
      "outreach.view",
      "outreach.manage",
      "mission.view",
      "mission.manage",
      "children.view_basic",
      "children.view_sensitive",
      "children.check_in",
      "children.check_out",
      "children.pickup.manage",
      "children.class.manage",
      "youth.manage",
      "campus_ministry.manage",
      "event.report.view",
      "event.report.manage",
      "event.report.export",
      "event.settings.manage",
    ],
  },
  {
    key: "reports",
    label: "Reports",
    permissions: ["report.view", "report.create", "report.export", "report.view_sensitive", "report.view_consolidated", "report.manage"],
  },
  {
    key: "audit",
    label: "Audit",
    permissions: ["audit.view", "audit.view_sensitive", "audit.export"],
  },
] as const;

export const permissionKeys: PermissionKey[] = [...new Set(permissionGroups.flatMap((group) => group.permissions))];

export const permissionDependencies = [
  { permission: "member.update", requires: "member.view", reason: "A user must view member records before updating them." },
  { permission: "member.export", requires: "member.view", reason: "Exports require read access first." },
  { permission: "programme.approve", requires: "programme.view", reason: "Approvers must be able to inspect programme summaries." },
  { permission: "programme.payment.verify", requires: "programme.payment.view", reason: "Payment verification requires payment visibility." },
  { permission: "programme.result.release", requires: "programme.grade", reason: "Result release requires grading visibility." },
  { permission: "service.publish", requires: "service.approve", reason: "Services should be approved before publication." },
  { permission: "service.report.approve", requires: "service.report.review", reason: "Service report approval requires review visibility." },
  { permission: "event.publish", requires: "event.approve", reason: "Events should be approved before publication." },
  { permission: "event.payment.verify", requires: "event.payment.view", reason: "Payment verification requires payment visibility." },
  { permission: "children.view_sensitive", requires: "children.view_basic", reason: "Sensitive child access requires basic child access first." },
  { permission: "event.report.export", requires: "event.report.view", reason: "Event exports require report visibility." },
  { permission: "finance.transaction.approve", requires: "finance.view_summary", reason: "Financial approvers need at least summary visibility." },
  { permission: "pastoral_case.update", requires: "pastoral_case.view_assigned", reason: "Pastoral edits require assigned-case visibility." },
  { permission: "pastoral_case.export_detailed", requires: "pastoral_case.view_restricted_notes", reason: "Detailed exports require restricted-note visibility first." },
  { permission: "safeguarding.case.manage", requires: "safeguarding.case.view", reason: "Safeguarding management requires explicit safeguarding visibility." },
  { permission: "small_group.report.approve", requires: "small_group.report.review", reason: "Approvers must review reports before approval." },
  { permission: "small_group.giving.verify", requires: "small_group.giving.view", reason: "Giving verification requires finance-summary visibility." },
] as const;

export const permissionConflicts = [
  {
    firstPermission: "finance.transaction.create",
    secondPermission: "finance.transaction.approve",
    description: "Creating and approving the same payment should require separation of duties.",
  },
  {
    firstPermission: "role.assign",
    secondPermission: "role.remove",
    description: "Role assignment and removal should be reviewed for sensitive roles.",
  },
  {
    firstPermission: "small_group.giving.record",
    secondPermission: "small_group.giving.verify",
    description: "Recording and verifying group giving totals should use separation of duties.",
  },
  {
    firstPermission: "programme.payment.verify",
    secondPermission: "programme.scholarship.approve",
    description: "Payment verification and scholarship approval should be reviewed for separation of duties.",
  },
  {
    firstPermission: "audit.export",
    secondPermission: "tenant.data.manage",
    description: "Managing data and exporting audit evidence can require a documented exception.",
  },
] as const;

export const systemRoleTemplates = [
  "Ministry Principal Authority",
  "Senior Pastor / Ministry Head",
  "Executive Pastor",
  "Church Administrator",
  "Regional Leader",
  "Zonal Leader",
  "Branch Pastor",
  "Associate Pastor",
  "Pastoral Care Minister",
  "Cell or Fellowship Leader",
  "Department Head",
  "Programme Coordinator",
  "Chief Finance Officer",
  "Accountant",
  "Treasurer",
  "HR Officer",
  "Events Coordinator",
  "Children's Ministry Leader",
  "Youth Ministry Leader",
  "Communications Officer",
  "Volunteer",
  "Member",
];

export const navigationModules = [
  ["Home", "/workspace/kings-grace"],
  ["People", "/workspace/kings-grace/people"],
  ["Visitors & New Converts", "/workspace/kings-grace/people/visitors"],
  ["Follow-Up", "/workspace/kings-grace/people/follow-up"],
  ["Pastoral Care", "/workspace/kings-grace/pastoral-care"],
  ["Prayer & Testimonies", "/workspace/kings-grace/pastoral-care/prayer"],
  ["Cells / Fellowships", "/workspace/kings-grace/groups"],
  ["Discipleship & Classes", "/workspace/kings-grace/programmes"],
  ["Services", "/workspace/kings-grace/services"],
  ["Departments", "/workspace/kings-grace/services/departments"],
  ["Volunteers", "/workspace/kings-grace/services/volunteers"],
  ["Events", "/workspace/kings-grace/events"],
  ["Outreach & Missions", "/workspace/kings-grace/events/outreach"],
  ["Children & Youth", "/workspace/kings-grace/events/children"],
  ["Giving", "later"],
  ["Finance", "later"],
  ["Programmes & Projects", "later"],
  ["Assets & Facilities", "later"],
  ["HR & Staff", "later"],
  ["Communications", "later"],
  ["Media", "later"],
  ["Reports", "later"],
  ["Authority", "/workspace/kings-grace/authority"],
  ["Approvals", "/workspace/kings-grace/authority/approvals"],
  ["Settings", "/workspace/kings-grace/settings"],
  ["Audit Trail", "/workspace/kings-grace/audit"],
] as const;

export const subscriptionPlans: SubscriptionPlan[] = [
  { id: "starter", name: "Kingdom Starter", minActivePeople: 1, maxActivePeople: 100, monthlyKes: 0, annualKes: 0, features: ["Core setup", "Users foundation", "Audit foundation"] },
  { id: "growth", name: "Kingdom Growth", minActivePeople: 101, maxActivePeople: 300, monthlyKes: 1000, annualKes: 10000, features: ["Growth-ready modules", "Branch foundation"] },
  { id: "community", name: "Kingdom Community", minActivePeople: 301, maxActivePeople: 750, monthlyKes: 2000, annualKes: 20000, features: ["Community scale", "Advanced reporting foundation"] },
  { id: "impact", name: "Kingdom Impact", minActivePeople: 751, maxActivePeople: 1500, monthlyKes: 3500, annualKes: 35000, features: ["Multi-branch operations", "Programme controls"] },
  { id: "network", name: "Kingdom Network", minActivePeople: 1501, maxActivePeople: 3000, monthlyKes: 6000, annualKes: 60000, features: ["Network structure", "Scoped leadership"] },
  { id: "mission", name: "Kingdom Mission", minActivePeople: 3001, maxActivePeople: 7500, monthlyKes: 10000, annualKes: 100000, features: ["Mission operations", "Enterprise support path"] },
  { id: "global", name: "Kingdom Global", minActivePeople: 7501, maxActivePeople: 15000, monthlyKes: 15000, annualKes: 150000, features: ["Global scale", "Custom governance support"] },
  { id: "enterprise", name: "Enterprise Ministry", minActivePeople: 15001, features: ["Custom pricing", "Dedicated implementation planning"] },
];

export const terminologyDefaults = {
  member: "Member",
  visitor: "Visitor",
  new_convert: "New Convert",
  pastor: "Pastor",
  senior_pastor: "Senior Pastor",
  small_group: "Cell",
  branch: "Branch",
  department: "Department",
  foundation_class: "Foundation Class",
  discipleship_programme: "Discipleship Programme",
};
