import { administrationPermissionKeys, subscriptionPlans, terminologyDefaults } from "./constants";
import type { AuditLog, Branch, Invitation, Membership, OrganizationUnit, Profile, Role, Tenant } from "./types";

export const profiles: Profile[] = [
  { id: "user-platform-owner", email: "timsila18@gmail.com", fullName: "Timothy Sila" },
  { id: "user-admin", email: "admin@kingsgrace.test", fullName: "Amina Otieno", phone: "+254700000001" },
  { id: "user-branch", email: "branch@kingsgrace.test", fullName: "David Mwangi" },
  { id: "user-volunteer", email: "volunteer@example.com", fullName: "Mercy Volunteer" },
];

export const tenants: Tenant[] = [
  {
    id: "tenant-kings-grace",
    legalName: "King's Grace Community Church",
    publicName: "King's Grace",
    slug: "kings-grace",
    primaryColor: "#10243f",
    secondaryColor: "#f3f1ec",
    accentColor: "#b7822f",
    country: "Kenya",
    region: "Nairobi County",
    physicalAddress: "Thika Road, Nairobi",
    contactEmail: "hello@kingsgrace.test",
    contactPhone: "+254700000000",
    website: "https://example.org",
    timeZone: "Africa/Nairobi",
    defaultCurrency: "KES",
    defaultLanguage: "en",
    dateFormat: "dd MMM yyyy",
    timeFormat: "24h",
    membershipTerminology: "Member",
    branchTerminology: "Campus",
    smallGroupTerminology: "Fellowship",
    ministryHeadTitle: "Lead Pastor",
    status: "approved",
    subscriptionStatus: "active",
    onboardingStatus: "approved",
    createdAt: "2026-07-11T08:00:00.000Z",
    updatedAt: "2026-07-11T08:00:00.000Z",
  },
  {
    id: "tenant-pending",
    legalName: "Hope Assembly",
    publicName: "Hope Assembly",
    slug: "hope-assembly",
    primaryColor: "#1b365d",
    secondaryColor: "#eef2f7",
    accentColor: "#a16f2b",
    country: "Kenya",
    region: "Kiambu County",
    physicalAddress: "Ruiru",
    contactEmail: "hello@hope.test",
    contactPhone: "+254700000002",
    timeZone: "Africa/Nairobi",
    defaultCurrency: "KES",
    defaultLanguage: "en",
    dateFormat: "dd MMM yyyy",
    timeFormat: "24h",
    membershipTerminology: "Believer",
    branchTerminology: "Branch",
    smallGroupTerminology: "Connect Group",
    ministryHeadTitle: "Senior Pastor",
    status: "under_review",
    subscriptionStatus: "trialing",
    onboardingStatus: "submitted",
    createdAt: "2026-07-11T09:00:00.000Z",
    updatedAt: "2026-07-11T09:00:00.000Z",
  },
];

export const roles: Role[] = [
  {
    id: "role-admin",
    tenantId: "tenant-kings-grace",
    name: "church_admin",
    displayName: "Church Administrator",
    systemTemplate: true,
    permissions: [
      "tenant.view",
      "organization.view",
      "organization.manage",
      "branch.view",
      "branch.manage",
      "settings.view",
      "settings.manage",
      "role.view",
      "role.manage",
      "audit.view",
      "people.view",
      "people.create",
      "people.update",
      "people.archive",
      "people.merge",
      "people.export_basic",
      "household.view",
      "household.manage",
      "visitor.view",
      "visitor.create",
      "visitor.update",
      "new_convert.view",
      "new_convert.create",
      "new_convert.manage",
      "follow_up.view",
      "follow_up.assign",
      "follow_up.manage",
      "consent.view",
      "consent.manage",
      "transfer.create",
      "transfer.approve",
      "child.view_basic",
      "child.manage",
      "form.manage",
      "import.people",
      "duplicate.manage",
      "pastoral_case.create",
      "pastoral_case.view_assigned",
      "pastoral_case.view_unit",
      "pastoral_case.view_all",
      "pastoral_case.update",
      "pastoral_case.refer",
      "pastoral_case.assign",
      "pastoral_case.close",
      "pastoral_case.reopen",
      "pastoral_case.view_restricted_notes",
      "pastoral_case.view_highly_confidential",
      "pastoral_case.export_summary",
      "pastoral_case.manage",
      "prayer_request.view",
      "prayer_request.assign",
      "prayer_request.manage",
      "testimony.review",
      "testimony.publish",
      "counselling.manage",
      "pastoral_visit.manage",
      "bereavement.manage",
      "welfare_request.view",
      "welfare_request.assess",
      "welfare_request.approve",
      "welfare_request.manage",
      "professional_referral.manage",
      "safeguarding.case.create",
      "safeguarding.case.view",
      "safeguarding.case.manage",
      "safeguarding.case.refer",
      "safeguarding.case.close",
      "safeguarding.audit.view",
      "small_group.view",
      "small_group.view_all",
      "small_group.create",
      "small_group.update",
      "small_group.manage",
      "small_group.archive",
      "small_group.assign_leader",
      "small_group.membership.manage",
      "small_group.join_request.manage",
      "small_group.transfer.manage",
      "small_group.attendance.record",
      "small_group.attendance.view",
      "small_group.report.submit",
      "small_group.report.review",
      "small_group.report.approve",
      "small_group.report.return",
      "small_group.report.lock",
      "small_group.giving.record",
      "small_group.giving.view",
      "small_group.giving.verify",
      "small_group.multiplication.manage",
      "small_group.settings.manage",
      "small_group.public_directory.manage",
      "small_group.export",
      "programme.view",
      "programme.create",
      "programme.update",
      "programme.publish",
      "programme.approve",
      "programme.archive",
      "programme.cohort.manage",
      "programme.trainer.assign",
      "programme.enrolment.view",
      "programme.enrolment.manage",
      "programme.enrolment.approve",
      "programme.payment.view",
      "programme.payment.verify",
      "programme.scholarship.view",
      "programme.scholarship.manage",
      "programme.scholarship.approve",
      "programme.attendance.capture",
      "programme.attendance.view",
      "programme.material.manage",
      "programme.assignment.manage",
      "programme.assessment.manage",
      "programme.grade",
      "programme.result.release",
      "programme.result.moderate",
      "programme.certificate.issue",
      "programme.certificate.revoke",
      "programme.graduation.manage",
      "programme.report.view",
      "programme.report.export",
      "programme.settings.manage",
      "programme.manage",
      "service.view",
      "service.create",
      "service.update",
      "service.approve",
      "service.publish",
      "service.cancel",
      "service.plan.manage",
      "service.order.manage",
      "service.sermon.view",
      "service.sermon.manage",
      "service.worship.manage",
      "service.report.create",
      "service.report.review",
      "service.report.approve",
      "service.report.export",
      "department.view",
      "department.create",
      "department.update",
      "department.archive",
      "department.assign_leader",
      "department.manage_members",
      "department.manage",
      "volunteer.view",
      "volunteer.manage",
      "volunteer.approve",
      "volunteer.availability.manage",
      "roster.view",
      "roster.create",
      "roster.publish",
      "roster.confirm",
      "roster.replace",
      "roster.manage",
      "rehearsal.manage",
      "equipment_checklist.manage",
      "media_request.manage",
      "protocol.manage",
      "service.incident.create",
      "service.incident.view",
      "service.incident.manage",
      "service.settings.manage",
      "event.view",
      "event.create",
      "event.update",
      "event.approve",
      "event.publish",
      "event.cancel",
      "event.registration.view",
      "event.registration.manage",
      "event.registration.approve",
      "event.payment.view",
      "event.payment.verify",
      "event.ticket.issue",
      "event.check_in",
      "event.check_out",
      "event.session.manage",
      "event.volunteer.manage",
      "event.speaker.manage",
      "event.transport.manage",
      "event.accommodation.manage",
      "event.meals.manage",
      "event.security.manage",
      "event.safeguarding.manage",
      "event.incident.create",
      "event.incident.view",
      "event.incident.manage",
      "outreach.view",
      "outreach.manage",
      "mission.view",
      "mission.manage",
      "children.view_basic",
      "children.view_sensitive",
      "children.check_in",
      "children.check_out",
      "children.pickup.manage",
      "children.class.manage",
      "youth.manage",
      "campus_ministry.manage",
      "event.report.view",
      "event.report.manage",
      "event.report.export",
      "event.settings.manage",
      "giving.category.view",
      "giving.category.manage",
      "giving.fund.view",
      "giving.fund.manage",
      "giving.destination.view",
      "giving.destination.manage",
      "giving.destination.approve",
      "giving.contribution.view_summary",
      "giving.contribution.view_individual",
      "giving.contribution.create",
      "giving.contribution.verify",
      "giving.contribution.correct",
      "giving.contribution.reverse",
      "giving.cash_count.manage",
      "giving.handover.view",
      "giving.handover.manage",
      "giving.receipt.issue",
      "giving.receipt.void",
      "giving.statement.generate",
      "giving.pledge.view",
      "giving.pledge.manage",
      "giving.partnership.view",
      "giving.partnership.manage",
      "giving.campaign.view",
      "giving.campaign.manage",
      "giving.reconciliation.view",
      "giving.reconciliation.manage",
      "giving.dispute.manage",
      "giving.refund.request",
      "giving.refund.approve",
      "giving.export_summary",
      "giving.export_detailed",
      "giving.export_individual",
      "giving.export_restricted_funds",
      "giving.export_statements",
      "giving.audit.view",
      "giving.settings.manage",
      ...administrationPermissionKeys,
    ],
  },
  {
    id: "role-branch",
    tenantId: "tenant-kings-grace",
    name: "branch_pastor",
    displayName: "Branch Pastor",
    systemTemplate: true,
    permissions: ["tenant.view", "organization.view", "branch.view", "people.view", "visitor.view", "new_convert.view", "follow_up.view", "follow_up.assign", "child.view_basic", "pastoral_case.create", "pastoral_case.view_assigned", "pastoral_case.view_unit", "pastoral_case.update", "pastoral_case.assign", "pastoral_case.refer", "pastoral_case.close", "prayer_request.view", "prayer_request.assign", "counselling.manage", "pastoral_visit.manage", "bereavement.manage", "welfare_request.view", "welfare_request.assess", "small_group.view", "small_group.create", "small_group.update", "small_group.assign_leader", "small_group.membership.manage", "small_group.join_request.manage", "small_group.transfer.manage", "small_group.attendance.view", "small_group.report.review", "small_group.report.approve", "small_group.multiplication.manage", "programme.view", "programme.enrolment.view", "programme.enrolment.manage", "programme.enrolment.approve", "programme.attendance.view", "programme.report.view", "service.view", "service.create", "service.update", "service.approve", "service.publish", "service.report.review", "service.report.approve", "department.view", "department.manage_members", "volunteer.view", "volunteer.manage", "roster.view", "roster.publish", "service.incident.view", "event.view", "event.create", "event.update", "event.approve", "event.publish", "event.registration.view", "event.registration.manage", "event.check_in", "event.session.manage", "event.volunteer.manage", "event.incident.view", "outreach.view", "outreach.manage", "mission.view", "children.view_basic", "children.check_in", "children.check_out", "youth.manage", "campus_ministry.manage", "event.report.view", "event.report.manage", "giving.category.view", "giving.fund.view", "giving.destination.view", "giving.destination.approve", "giving.contribution.view_summary", "giving.handover.view", "giving.campaign.view", "accounting.account.view", "accounting.report.view", "budget.view", "budget.create", "payment_request.create", "payment_request.review", "procurement.request.create", "procurement.receipt.manage", "supplier.view", "inventory.view", "asset.view", "facility.view", "facility.booking.manage", "maintenance.manage", "project.view", "transport.view", "hr.leave.view", "hr.leave.approve"],
  },
  {
    id: "role-member",
    tenantId: "tenant-kings-grace",
    name: "member",
    displayName: "Member",
    systemTemplate: true,
    permissions: ["tenant.view"],
  },
];

export const memberships: Membership[] = [
  { id: "membership-admin", tenantId: "tenant-kings-grace", userId: "user-admin", status: "active", roleIds: ["role-admin"] },
  { id: "membership-branch", tenantId: "tenant-kings-grace", userId: "user-branch", status: "active", roleIds: ["role-branch"] },
];

export const organizationUnits: OrganizationUnit[] = [
  { id: "unit-head", tenantId: "tenant-kings-grace", unitType: "head_office", name: "Head Office", code: "KGC-HQ", leaderName: "Amina Otieno", administratorName: "Amina Otieno", location: "Nairobi", status: "active", visibility: "tenant", reportingOrder: 1, createdBy: "user-admin", updatedBy: "user-admin", createdAt: "2026-07-11T08:10:00.000Z", updatedAt: "2026-07-11T08:10:00.000Z" },
  { id: "unit-east", tenantId: "tenant-kings-grace", parentId: "unit-head", unitType: "region", name: "Eastern Region", code: "KGC-ER", leaderName: "David Mwangi", status: "active", visibility: "tenant", reportingOrder: 2, createdBy: "user-admin", updatedBy: "user-admin", createdAt: "2026-07-11T08:20:00.000Z", updatedAt: "2026-07-11T08:20:00.000Z" },
  { id: "unit-imaara", tenantId: "tenant-kings-grace", parentId: "unit-east", unitType: "branch", name: "Imaara Campus", code: "KGC-IMA", leaderName: "David Mwangi", status: "active", visibility: "tenant", reportingOrder: 3, createdBy: "user-admin", updatedBy: "user-admin", createdAt: "2026-07-11T08:30:00.000Z", updatedAt: "2026-07-11T08:30:00.000Z" },
  { id: "unit-ruiru", tenantId: "tenant-kings-grace", parentId: "unit-east", unitType: "branch", name: "Ruiru Campus", code: "KGC-RUI", leaderName: "Grace Wanjiku", status: "active", visibility: "tenant", reportingOrder: 4, createdBy: "user-admin", updatedBy: "user-admin", createdAt: "2026-07-11T08:35:00.000Z", updatedAt: "2026-07-11T08:35:00.000Z" },
  { id: "unit-youth", tenantId: "tenant-kings-grace", parentId: "unit-head", unitType: "department", name: "Youth Ministry", code: "KGC-YTH", leaderName: "Vacant", status: "active", visibility: "tenant", reportingOrder: 5, createdBy: "user-admin", updatedBy: "user-admin", createdAt: "2026-07-11T08:40:00.000Z", updatedAt: "2026-07-11T08:40:00.000Z" },
];

export const branches: Branch[] = [
  { id: "branch-imaara", tenantId: "tenant-kings-grace", unitId: "unit-imaara", name: "Imaara Campus", code: "IMA", leaderName: "David Mwangi", administratorName: "Mercy Njeri", address: "Imaara Daima", phone: "+254711000001", email: "imaara@kingsgrace.test", serviceTimes: ["Sunday 09:00", "Wednesday 18:00"], status: "active", seatingCapacity: 450, timeZone: "Africa/Nairobi" },
  { id: "branch-ruiru", tenantId: "tenant-kings-grace", unitId: "unit-ruiru", name: "Ruiru Campus", code: "RUI", leaderName: "Grace Wanjiku", administratorName: "Peter Kariuki", address: "Ruiru Town", phone: "+254711000002", email: "ruiru@kingsgrace.test", serviceTimes: ["Sunday 10:00"], status: "planting", seatingCapacity: 220, timeZone: "Africa/Nairobi" },
];

export const invitations: Invitation[] = [
  { id: "invite-1", tenantId: "tenant-kings-grace", email: "volunteer@example.com", roleId: "role-member", scopeType: "branch", scopeId: "branch-imaara", status: "pending", expiresAt: "2026-07-25T08:00:00.000Z", tokenPreview: "kf_inv_...8d2" },
];

export const auditLogs: AuditLog[] = [
  { id: "audit-1", tenantId: "tenant-kings-grace", actorId: "user-platform-owner", actorName: "Timothy Sila", action: "church.approved", entityType: "tenant", entityId: "tenant-kings-grace", result: "success", reason: "Development seed approval", scopeType: "platform", createdAt: "2026-07-11T08:05:00.000Z" },
  { id: "audit-2", tenantId: "tenant-kings-grace", actorId: "user-admin", actorName: "Amina Otieno", action: "organization_unit.created", entityType: "organization_unit", entityId: "unit-imaara", result: "success", scopeType: "unit", scopeId: "unit-imaara", createdAt: "2026-07-11T08:30:00.000Z" },
  { id: "audit-3", tenantId: "tenant-kings-grace", actorId: "user-admin", actorName: "Amina Otieno", action: "invitation.created", entityType: "invitation", entityId: "invite-1", result: "success", scopeType: "branch", scopeId: "branch-imaara", createdAt: "2026-07-11T10:00:00.000Z" },
  { id: "audit-4", tenantId: "tenant-kings-grace", actorId: "user-admin", actorName: "Amina Otieno", action: "role.assignment.submitted", entityType: "approval_request", entityId: "approval-youth-role", result: "success", scopeType: "unit", scopeId: "unit-youth", createdAt: "2026-07-11T11:00:00.000Z" },
  { id: "audit-5", tenantId: "tenant-kings-grace", actorId: "user-admin", actorName: "Amina Otieno", action: "delegation.created", entityType: "delegation", entityId: "delegation-programme-east", result: "success", scopeType: "unit_descendants", scopeId: "unit-east", createdAt: "2026-07-11T11:20:00.000Z" },
];

export const tenantTerminology = {
  "tenant-kings-grace": {
    ...terminologyDefaults,
    branch: "Campus",
    small_group: "Fellowship",
    senior_pastor: "Lead Pastor",
  },
};

export function getTenantBySlug(slug: string) {
  return tenants.find((tenant) => tenant.slug === slug);
}

export function getTenantSubscription(tenantId: string) {
  return {
    tenantId,
    plan: subscriptionPlans[0],
    status: tenants.find((tenant) => tenant.id === tenantId)?.subscriptionStatus ?? "trialing",
    billingCycle: "monthly" as const,
  };
}
